# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         HTML-Template-Pro
version:      0.48
version_from: lib/HTML/Template/Pro.pm
installdirs:  site
requires:
    File::Spec:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
